BOT_TOKEN: 
  - MTAyMzIzNTg1MTE5NjU3OTg5MA.G_0CJr.zex4nkShjTvIlbzAl-ZDmYabPR8FGuNe3_ujXM
CHANNEL_ID: 
  - 1032816068131041301
MODE: simsimi
REPLY: Y
SIMSIMI_LANG: en
DELAY: 35
DEL_AFTER: 
REPOST_LAST_CHAT: 100
